# Generated by Django 5.2.7 on 2025-10-03 06:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.CharField(default=core.models.generate_cuid, editable=False, max_length=27, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='STAFF', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nm_hospital_staff',
                'constraints': [models.UniqueConstraint(fields=('hospital', 'user'), name='uq_hospital_user_staff')],
            },
        ),
    ]
