version: '3.8'

services:
  web:
    build: .
    command: gunicorn hms_ultra.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=config.production_settings
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - DB_NAME_FILE=/run/secrets/postgres_db
      - DB_USER_FILE=/run/secrets/postgres_user
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    secrets:
      - django_secret_key
      - postgres_db
      - postgres_user
      - postgres_password
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ../ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped

  celery:
    build: .
    command: celery -A hms_ultra worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=config.production_settings
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - DB_NAME_FILE=/run/secrets/postgres_db
      - DB_USER_FILE=/run/secrets/postgres_user
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    secrets:
      - django_secret_key
      - postgres_db
      - postgres_user
      - postgres_password
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A hms_ultra beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=config.production_settings
      - SECRET_KEY_FILE=/run/secrets/django_secret_key
      - DB_NAME_FILE=/run/secrets/postgres_db
      - DB_USER_FILE=/run/secrets/postgres_user
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    secrets:
      - django_secret_key
      - postgres_db
      - postgres_user
      - postgres_password
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  postgres_db:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
  django_secret_key:
    external: true
